### ISSUE TITLE
OTA support for XMC4800 kit

### ISSUE THREAD

**Issue by Rutvij-dev** [Infineon/amazon-freertos#11]
Hi,
I have downloaded the repo for xmc4800 kit and i am able to run the basic hello world MQTT messaging demo with AWS.
However in this repo i was unable to find `aws_ota_pal.c `so i assume there is not support available for OTA from AWS for XMC kit .

So is there any code/doc available ?
if not any plans to provide this feature using Trust-M HSM ?

Thanks

**Comment by ayushev** [comment]
The Trust M can support the OTA out of the box if the target platform does support it. XMC4800 for the time-being doesn’t do this.
