### ISSUE TITLE
Optiga Trust M support in BLE based End device

### ISSUE THREAD

**Issue by Darsh-Dev** [Infineon/amazon-freertos#4]
Hi @ayushev ,

We have STM based BLE end sensor device. In this model, AWS FreeRTOS provides BLE MQTT demo and it uses an Android App or IOS App for communicating with the AWS cloud Also for device authentication, it uses AWS Cognito. 

We are porting the TrustM on STM32WB55 BLE based sensor device. We would like to understand the, how it will help us in the Amazon-freeRTOS demo?

Have you tested with AWSFreeRTOS without AWS cognito model?

Thanks,
Darshak

**Comment by pwiegele** [comment]
Hi Darsh-Dev,

the Optiga Trust M implementation protects the link between your BLE based sensor device to AWS IoT Core. (TLS with hardware crypto support). The link between your Android or IOS app and AWS uses a different communication channel and is independent.

Please correct me if I missunderstood you.

BR Paul

**Comment by Darsh-Dev** [comment]
Hi @butlerpaul 

Correct, Optiga Trust M protects using TLS with hardware crypto support.In AWS free-RTOS, BLE sensor communicate with Android APP over BLE + MQTT model. Android App support cognito mode for provisioning between AWS cloud , App and Sensor device. 

We would like to add the Optiga TrustM support. But How we can achieve features like WiFi provisioning model in BLE sensor case using TrustM?

Thanks,
Darshak

**Comment by Darsh-Dev** [comment]
We have ported the Optiga TrustM in the BLE based End device. We would like to use Optiga TrustM features to communicate with AWS cloud via Mobile APP based solution. Need guidance, how we can achieve it? 

Any modification are needed in the AWS Android App: https://github.com/aws/amazon-freertos-ble-android-sdk.

**Comment by ayushev** [comment]
Hello @Darsh-Dev 
sorry for not answering that long, I hope you were managed to resolve the issue. In my opinion you don't need to change much in the android app itself, but I'm not an expert here. Did you succeed, do you need further support here?

**Comment by Darsh-Dev** [comment]
@ayushev 

We have resolved the issue for Android App. We are working on IOS app customization. No further query. Thanks
