### ISSUE TITLE
How to resolve error MBEDTLS_ERR_X509_INVALID_FORMAT ?

### ISSUE THREAD

**Issue by ayushev** [Infineon/amazon-freertos#5]
Refer to https://github.com/Infineon/optiga-trust-m/issues/25

Hi @Darsh-Dev you are welcome
 this tool "AWS CertificateConfigurator.html" is required only if you work with the software only security and isn't required for the hardware powered crypto.
You need to follow [this](https://github.com/Infineon/amazon-freertos/blob/feature/trustm/vendors/infineon/boards/xmc4800_plus_optiga_trust_m/README.md) guideline 
Please feel free to ask questions if something isn't clear here

**Comment by Darsh-Dev** [comment]
Hi @ayushev,

Unfortunately, I encountered the same error.

As discussed in the mentioned link I did the steps of **Option #2: Onboard Private Key Generation** and added keyCLIENT_CERTIFICATE_PEM and keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM. 
I Encountered "_Warning: no persistent storage is available for the JITP certificate. The certificate in aws_clientcredential_keys.h will be used instead_" but again vDevModeKeyProvisioning() did work well but while in TLS_Connect had same (MBEDTLS_ERR_X509_INVALID_FORMAT) error due to MBEDTLS_ERR_ASN1_OUT_OF_DATA.

One thing i noted here, while performing vDevModeKeyProvisioning() ...> xProvisionCertificate() it tries to destroy objects (xDestroyProvidedObjects) before creating new if exists, but I had to comment xDestroyProvidedObjects because it seemed stuck(hangs)in i2c repeat condition (?!)(which I found no where mentioned ), and after commenting this I got vDevModeKeyProvisioning() successful call return.  could this be an issue?


Apart from above, I m using LTE-M to communicate and to enable demo with this, in _iot_demo_freertos.c_ file before running demoEntryPoint() I added credentials and interface by my own (cause LTE is not supported yet) as per below
```
        pNetworkInterface = IOT_NETWORK_INTERFACE_AFR;
        connectionParams.pHostName = clientcredentialMQTT_BROKER_ENDPOINT;
        connectionParams.port = clientcredentialMQTT_BROKER_PORT;

        if( connectionParams.port == 443 )
        {
            credentials.pAlpnProtos = socketsAWS_IOT_ALPN_MQTT;
        }
        else
        {
            credentials.pAlpnProtos = NULL;
        }
        credentials.maxFragmentLength = 0;
        credentials.disableSni = false;
        credentials.pRootCa = keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM;
        credentials.rootCaSize = sizeof(keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM);
        credentials.pClientCert = keyCLIENT_CERTIFICATE_PEM;
        credentials.clientCertSize = sizeof( keyCLIENT_CERTIFICATE_PEM );
        credentials.pPrivateKey = NULL;
        credentials.privateKeySize = 0;

        /* Run the demo. */
        status = demoEntryPoint( true,
                                 clientcredentialIOT_THING_NAME,
                                 &( connectionParams ),
                                 &( credentials ),
                                 pNetworkInterface );
```

Above now with rootCA and device certificate.

So is there anything I might have missed.

Thanks

**Comment by Darsh-Dev** [comment]
Hi,
One more update from my side. 
I wrote a sample test code in same mbedtls version source file as below 
```
void checkTLS( void )
{
	int pkret;
	mbedtls_x509_crt _cacert;
	mbedtls_x509_crt_init(&_cacert);
	pkret = mbedtls_x509_crt_parse(&_cacert, (const unsigned char *) keyCLIENT_CERTIFICATE_PEM,
	                           sizeof (keyCLIENT_CERTIFICATE_PEM));
	if(pkret != 0) {
			printf("\n x509 certificate parsing, error=%d", pkret);
	}
	else if(pkret == 0) {
		printf("\n x509 certificate parsed, pass,\n");
	}
}
```

This function returns 0 and passes the parsing for the same certificate generated in the above process.
To validate further I intensely put the error-prone certificate and got 0x2180 error.

Thanks.

**Comment by ayushev** [comment]
Please have a look on the updated manual https://github.com/Infineon/amazon-freertos/commit/ce23016da800951ab563b7bcd9217f27891a43d3
You actually shouldn't provision certificate every run, this is only a one-time action.
YOu can also try out the Multi-Account Registration, you sample should be equiped with the default certificate from infineon which can be used for this.

**Comment by Darsh-Dev** [comment]
Hi,

This is mentioned in the earlier link you just provided and I did follow that only for once.
Then after I made keyprovisioningFORCE_GENERATE_NEW_KEY_PAIR to 0
But in that one shot itself it is behaving like that and my after error it closes my socket with error and not further work.


Thanks.

**Comment by ayushev** [comment]
If you have empty certificates and keys defined, and no generate_new_key_pair macro, then you can't come to the function ProvisionCertificate for every run.
Sorry, I'm a bit lost.
Can you help me to understand what is right now the problem.
The name of the ticket is a an error of the mbedTLS, the certificate you have generated and attached beforhand can't be used by trust-m for freertos, as it's RSA based certificate. [This](https://github.com/Infineon/amazon-freertos/blob/feature/trustm/vendors/infineon/boards/xmc4800_plus_optiga_trust_m/dev-mode-key-provisioning.md#dev-mode-key-provisioning-option2) guidance explains how to genearte an ECC based certificate.
So do you still have the same problem as you described originally, or it is a different one?

**Comment by Darsh-Dev** [comment]
Hi,
Below is the sequence I followed,
1.  Followed [this](https://github.com/Infineon/amazon-freertos/blob/feature/trustm/vendors/infineon/boards/xmc4800_plus_optiga_trust_m/dev-mode-key-provisioning.md#dev-mode-key-provisioning-option2) link 
2. keyprovisioningFORCE_GENERATE_NEW_KEY_PAIR made 1 and got 6 lines of Device public key
3. Created root CA and registered with AWS IoT and activated
4. Added deviceCert.pem and rootCA in in keyCLIENT_CERTIFICATE_PEM and keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM respectively 
5. Created thing and attached policy in AWS IoT and added above-generated deviceCert.pem to AWS IoT console while creating a thing.
6. keyprovisioningFORCE_GENERATE_NEW_KEY_PAIR made 0
7. Run code into device and it performed vDevModeKeyProvisioning() the first time and got the error afterward in MBEDTLS
8. Made keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM, keyCLIENT_CERTIFICATE_PEM, and keyCLIENT_PRIVATE_KEY_PEM macros in the configuration file for keys are defined to "" (empty string with quote ) in aws_clientcredential_keys.h and keyprovisioningFORCE_GENERATE_NEW_KEY_PAIR 0 
9. Again run the code but this time it vDevModeKeyProvisioning() is passed without doing anything (?!)
10. Encounterd <No-Low-Level-Code> in DEMO_RUNNER_RunDemos while hitting mbedtls_x509_crt_parse().

Is there anything I might have missed?

Furthermore, I am no more using the above-mentioned certificate but using the one generated from [this](https://github.com/Infineon/amazon-freertos/blob/feature/trustm/vendors/infineon/boards/xmc4800_plus_optiga_trust_m/dev-mode-key-provisioning.md#dev-mode-key-provisioning-option2) link.

Thanks

**Comment by ayushev** [comment]
Thank you for the summary! In general the flow look ok, except for errors, they shouldn't appear.
The step 6. IS it that error of fail to pars a certificate? Can you put here again what is the line you stuck, and what is exatcly the input ti the mbedtls prior recieving the error?

**Comment by ayushev** [comment]
@spalishchuk you recently followed the same flow, didn't you. Is it correct? Did you experience such errors?

**Comment by spalishchuk** [comment]
@Darsh-Dev may you attach here file aws_clientcredentional_keys.h at step 4.
*notice: every bootup with keyprovisioningFORCE_GENERATE_NEW_KEY_PAIR 1 in firmware will make previous device certificate unactual.
May You enable log for mbedTLS (define MBEDTLS_DEBUG_C) and attach file here. Problem appear when you trying to handshake with server or in vDevModeKeyProvisioning()?

ERROR: Object with label '0xE0E9' not found.
Write certificate...
Warning: no persistent storage is available for the JITP certificate. The certificate in aws_clientcredential_keys.h will be used instead.
I have the same problem, in my case it work properly.

**Comment by spalishchuk** [comment]
Also, did you register rootCA at AWS?

**Comment by Darsh-Dev** [comment]
Hi @spalishchuk  @ayushev,

From the code what I believe vDevModeKeyProvisioning() is just communicates with Trus-m and creates a label, session, and object, TLS will not come in the picture here.

But one it starts DEMO_RUNNER  it will Go to SOCKETS_Create and then SOCKETS_Connect.
Here Socket connects call will call TLS_Connect and in this, it will parse x509 certificate.

After performing steps as per **Option #2: Onboard Private Key Generation** now I am getting No-Low-Level-Code error after once time provisioning done.

The error I am getting is at "failed to parse custom server certificates" on line number 824, while mbedtls_x509_crt_parse()  with MBEDTLS_ERR_X509_INVALID_FORMAT as explained earlier in TLS Negotiation.

I tried to enable the logs but unfortunately, the logging task is crashing currently.

And yes rootCA is registered with AWS as per step no:3

Thanks.

**Comment by ayushev** [comment]
@Darsh-Dev 
Can you please provide what exactly do you feed to the mbedtls_x509_crt_parse function as a certificate. This might shed some light on the problem.

**Comment by Darsh-Dev** [comment]
Hi,
While TLC_Connect this is the function sequence I am seeing from **iot_tls.c** ,
1. prvInitializeClientCredential() 
2. xFindObjectWithLabelAndClass() // Get the handle of the device private key which is result = ok
3. C_GetAttributeValue() // Query the device private key type , it selects here "**MBEDTLS_PK_ECKEY**"
4. mbedtls_pk_info_from_type() // Map the mbedTLS algorithm to its internal metadata
5. prvReadCertificateIntoContext() // here we are encountring INVALID_FORMAT error for parsing 
```
     prvReadCertificateIntoContext( pxCtx, pkcs11configLABEL_DEVICE_CERTIFICATE_FOR_TLS,
                                                 CKO_CERTIFICATE,
                                                 &pxCtx->xMbedX509Cli );
```
Above point 5th function _(prvReadCertificateIntoContext)_ interns call below sequance,
1. xFindObjectWithLabelAndClass() //Get the handle of the certificate
2. C_GetAttributeValue() //Query the certificate size an malloc
3. C_GetAttributeValue() //Export the certificate
4. mbedtls_x509_crt_parse //Decode the certificate // from here we are getting above 5th call's error. 
```
        xResult = mbedtls_x509_crt_parse( pxCertificateContext,
                                          ( const unsigned char * ) xTemplate.pValue,
                                          xTemplate.ulValueLen );
```

Here in this configuration 
1. vDevModeKeyProvisioning() is enabled (i.e non commented),
2. keyprovisioningFORCE_GENERATE_NEW_KEY_PAIR is 0 (i.e not genrating public key from device)

If you have can you tell the expected call flow for _iot_tls.c_ ?


Thanks,

**Comment by spalishchuk** [comment]
![image](https://user-images.githubusercontent.com/68946320/89039268-6b551480-d34a-11ea-9a6d-46c43a43abc0.png)

**Comment by spalishchuk** [comment]
Is your device certificate looks like this 
![image](https://user-images.githubusercontent.com/68946320/89039534-ea4a4d00-d34a-11ea-98b1-0a54502ff431.png)

**Comment by Darsh-Dev** [comment]
Hi, 
Thanks for the replay,
![debugging_cert_error](https://user-images.githubusercontent.com/52735713/89041647-5c2e9080-d363-11ea-9d1c-584f869df389.png)

Here I even printed the contents and they are mentioned below in string format which seemed suspectable.

```
)*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
!@"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
!@"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
!@"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
!@"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
!@"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
!@"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
!@"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
!@"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
!@"#$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_;
```
Also currently in my aws_clientcredential_keys.h file currently all certificate macros are assigned as "" (i.e. empty string ) as [suggested](https://github.com/Infineon/amazon-freertos/blob/feature/trustm/vendors/infineon/boards/xmc4800_plus_optiga_trust_m/dev-mode-key-provisioning.md#dev-mode-key-provisioning-option2) in the guide after one-time provision using trust-m.

#define keyCLIENT_CERTIFICATE_PEM ""
#define keyCLIENT_PRIVATE_KEY_PEM ""
#define keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM  ""

Any suggestions?

Thanks

**Comment by lundinc2** [comment]
Hi, bumping in from the other threads that were opened about this.
@Darsh-Dev what version of the code are you running?

 >After performing steps as per Option #2: Onboard Private Key Generation now I am getting No-Low-Level-Code error after    once time provisioning done. 

`No-Low-Level-Code` is a log from a newer version of A:FR, to me it looks like the Optiga M branches are based on the 202002.00 release of A:FR, which does not have that log message.

**Comment by spalishchuk** [comment]
@Darsh-Dev length of certificate is strange (1719 bytes). You may check in function in file oit_tls.c prvReadCertificateIntoContext()->
![image](https://user-images.githubusercontent.com/68946320/89051595-2f777a80-d35d-11ea-8042-f87cffd42bad.png)
Then in C_GetAttributeValue() look at PKCS11_PAL_GetObjectValue(). In my case xPalHandle = 5, returned ulLength = 738.
![image](https://user-images.githubusercontent.com/68946320/89051726-5766de00-d35d-11ea-9dce-bb15fe88acea.png)

If Object read ok, and definition of pkcs11configLABEL_DEVICE_CERTIFICATE_FOR_TLS is not touched, I recomend to do provisioning again (keyCLIENT_CERTIFICATE_PEM and keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM ). Do you using ECC keys or RSA?

**Comment by spalishchuk** [comment]
@Darsh-Dev Do do your using PAL I2C layer from demo or own? Also, your can check writing and reading objects to optiga at label 0xE0E1, 0xE0E8.
![image](https://user-images.githubusercontent.com/68946320/89053838-7c108500-d360-11ea-8f5d-72d951458de2.png)

[optiga-trust-m-fb662c7c208c4f3b321e604b04a55f7796beed13.zip](https://github.com/Infineon/amazon-freertos/files/5007892/optiga-trust-m-fb662c7c208c4f3b321e604b04a55f7796beed13.zip)

**Comment by Darsh-Dev** [comment]
Hi,
I tried to write and read the 0xE0E1 and got error _Failed with return value - 0x8007_, after debugging, found that metadata for 0xE0E1 OID was causing issue while running _example_optiga_util_protected_update()_ in optiga self-test.

I did run this test to ensure optiga functionality at the early porting stage and it was passing all the 21 test cases.

To resolve the above issue I overwrite the below sample metadata for 0xE0E1.

```

static uint8_t metadata [] = {
		0x20, 0x08, // TL metadata TLV-Object
		0xD1, 0x01, 0x00, // TLV Read = ALW
		0xD0, 0x03, 0xE1, 0xFC, 0x07 // TLV Change = LcsO < op
};

```
After doing the above I can write and read 0xE0E1 without any error and parsing of device certificate got succeeded.
But still, I m facing TLS_HANDSHAKE issue and got below error.

```
0 210 [Tmr Svc]
Wi-Fi module initialized. Connecting to AP...
.1 7961 [Tmr Svc]
Wi-Fi Connected to AP. Creating tasks that use network...
2 7973 [Tmr Svc]
IP Address acquired 192.168.43.197
3 8203 [iot_thread]
[INFO ][DEMO][8203] ---------STARTING DEMO---------

 

4 8205 [iot_thread]
[INFO ][INIT][8205] SDK successfully initialized.
.5 13234 [iot_thread]
[INFO ][DEMO][13234] Successfully initialized the demo. Network type for the demo: 1
6 13234 [iot_thread]
[INFO ][MQTT][13234] MQTT library successfully initialized.
7 13234 [iot_thread]
[INFO ][DEMO][13234] MQTT demo client identifier is LTE_Thing (length 9).
.8 16064 [iot_thread]
ERROR: Handshake failed with error code -30592
9 16066 [iot_thread]
[ERROR][NET][16066] Failed to establish a new connection. Socket status: -1002.
10 16066 [iot_thread]
[ERROR][MQTT][16066] Failed to establish new MQTT connection, error NETWORK ERROR.
11 16066 [iot_thread]
[ERROR][DEMO][16066] MQTT CONNECT returned error NETWORK ERROR.
12 16066 [iot_thread]
[INFO ][MQTT][16066] MQTT library cleanup done.
13 16066 [iot_thread]
[ERROR][DEMO][16066] Error running the demo.
14 16075 [iot_thread]
[INFO ][INIT][16075] SDK cleanup done.
15 16075 [iot_thread]
[INFO ][DEMO][16075] -------DEMO FINISHED-------

```

I tried this demo on XMC4800 IoT Connectivity Kit as mentioned [here](https://github.com/Infineon/amazon-freertos/tree/feature/trustm/vendors/infineon/boards/xmc4800_plus_optiga_trust_m).

Also please find the attached log of mbedtls failure debug logs
[mbedtlsLogs.txt](https://github.com/Infineon/amazon-freertos/files/5012237/mbedtlsLogs.txt)

Any suggestions?

Thanks

**Comment by spalishchuk** [comment]
Hi, it's good! 
At the end of file ssl_cli.c you can find a state machine of handshake process. Also you can try to comment this line in code https://github.com/Infineon/amazon-freertos/blob/ce23016da800951ab563b7bcd9217f27891a43d3/vendors/infineon/secure_elements/pkcs11/iot_pkcs11_trustm.c#L2511

**Comment by ayushev** [comment]
@Darsh-Dev 

this is good step forward!
The error you receive is form mbedTLS, it is likly an fatal alert sent by the server. To understand what exactly has been sent eihter a sniffer on the TLS session, or emable logs on your board. I do see your answer some time ago:

> I tried to enable the logs but unfortunately, the logging task is crashing currently.

YOu can try to enable less logs by enabling mbedtls logs 
and reducing the level of verbosity [here ](https://github.com/Infineon/amazon-freertos/blob/feature/trustm/libraries/freertos_plus/standard/tls/src/iot_tls.c#L48) from 4 to 3 or even 2.
Another reason why logging crashes is that you [didn't provide enough memory to the logging task ](https://github.com/Infineon/amazon-freertos/blob/feature/trustm/vendors/infineon/boards/xmc4800_plus_optiga_trust_m/aws_demos/application_code/main.c#L52)

**Comment by Darsh-Dev** [comment]
Hi,
So i would suggest to provide a routine or stuff in optiga self test code, which should server as de-init for meta data and undo what it did in initialization or write state stage.
For the first time user perspective self test will be use by everyone in porting's initial stage to validate.

Thank you for the support everyone.

Thanks.

**Comment by ayushev** [comment]
hi @Darsh-Dev 
you are welcome and your feedaback is already going to be implemented soon. The example will bring the metadata back in the original state.
Regarding this issue, are you going to provide the logs or did you solve it?

**Comment by Darsh-Dev** [comment]
Hi,
I solved it by running optiga self test again but this time i wrote below meta data in **example_optiga_util_write_data.c** file .

```
static uint8_t metadata [] = {
		0x20, 0x08, // TL metadata TLV-Object
		0xD1, 0x01, 0x00, // TLV Read = ALW
		0xD0, 0x03, 0xE1, 0xFC, 0x07 // TLV Change = LcsO < op
};
```

I m not much aware weather the above written metadata is expected or not, but in my case it worked.
Now after writing this meta data if i switched to aws_demo it moved ahead.

Thanks
