### ISSUE TITLE
Pre-provisioned in Trust M certificate

### ISSUE THREAD

**Issue by Darsh-Dev** [Infineon/amazon-freertos#9]
Hi,

We would like to "Use pre-provisioned in Trust M certificate and AWS IoT Multi-Account Registration" model for the production of the kit.

I have go-through  [OPTIGA™ Trust M sample registration on AWS IoT
](https://github.com/Infineon/personalize-optiga-trust/blob/master/register-s2go/aws-iot.md#optiga-trust-m-sample-registration-on-aws-iot) steps. 

Please explain about the 
**Option 1. You DO have the certificate from your OPTIGA™ Trust** 
from where, we can find the the "certificate.pem" file or how to pass the "registration of Shield2Go Board"

**Option 2. You DON'T have the certificate from your OPTIGA™ Trust**
Can you please share the source code of the "xmc4800_plus_optiga_trust_m_get_certificate.hex"? We would like to replicate the same method for our kit.

**Comment by ayushev** [comment]
For the first opt

**Comment by ayushev** [comment]
The key defeerentiation of the MAR feature, is that you need to know and register in advance with the AWS IoT Core your device certificates.
The difference between options is that whether you can get somehow (out of bound) the certificate from your board. It is possible, for isntance, if you have one of [these](https://www.infineon.com/cms/en/product/evaluation-boards/s2go-cloud-optiga-m/) boards. 
Otherwise, you need to extract the certificate from your board using one of examples:
1) as per your request, here is the source code from my private repository based on the getting started guide. [Link to the fucntion call](https://github.com/ayushev/get-optiga-certificate-iotkit/blob/master/xmc4800_iot_kit/optiga_shell.c#L497), the repository [itself](https://github.com/ayushev/get-optiga-certificate-iotkit). Please mind that it is my private repo, which I don't maintain regularly.
2) Take the same implementation from the amazon-freertos repository. Just uncomment [this line](https://github.com/Infineon/amazon-freertos/blob/feature/trustm/vendors/infineon/boards/xmc4800_plus_optiga_trust_m/aws_demos/application_code/main.c#L128)

**Comment by Darsh-Dev** [comment]
Thanks @ayushev 

We have checked the AWS MQTT demo using pre-provisining certificate with XMC4800 + TRUSTM kit.

Now, we want to verify the device certificate 0xE0E0 with [Infineon OPTIGA(TM) Trust M CA 101.pem](https://github.com/Infineon/optiga-trust-m/blob/master/certificates/Infineon%20OPTIGA(TM)%20Trust%20M%20CA%20101.pem)

we are verifying using,
openssl verify -CAfile <optiga_RootCa.pem> <dev_certificate.pem> But its getting failed. 

```

> root@hp:~/Desktop$ openssl verify -CAfile optiga_RootCa.pem certificate.pem
> C = DE, O = Infineon Technologies AG, OU = OPTIGA(TM), CN = Infineon OPTIGA(TM) Trust M CA 101
> error 2 at 1 depth lookup: unable to get issuer certificate
> error certificate.pem: verification failed
> 

```

**Comment by ayushev** [comment]
Hi @Darsh-Dev 
openssl does require by default to have a complete chain to run this command. So you need to give as optiga_RootCa.pem the complete chain inclufing the [Infineon ECC Root CA C v01 00](https://github.com/Infineon/optiga-trust-m/raw/master/certificates/Infineon%20ECC%20Root%20CA%20C%20v01%2000.pem) (I just added in pem for your convinience) and the [ Infineon OPTIGA(TM) Trust M CA 101.pem](https://github.com/Infineon/optiga-trust-m/blob/master/certificates/Infineon%20OPTIGA(TM)%20Trust%20M%20CA%20101.pem)
Here is an example of how this chain can look like:
```
-----BEGIN CERTIFICATE-----
MIICeDCCAf6gAwIBAgIEFNFvOzAKBggqhkjOPQQDAzB3MQswCQYDVQQGEwJERTEh
MB8GA1UECgwYSW5maW5lb24gVGVjaG5vbG9naWVzIEFHMRswGQYDVQQLDBJPUFRJ
R0EoVE0pIERldmljZXMxKDAmBgNVBAMMH0luZmluZW9uIE9QVElHQShUTSkgRUND
IFJvb3QgQ0EwHhcNMTgwOTAxMTQ0NjQwWhcNNDMwNzI1MjM1OTU5WjByMQswCQYD
VQQGEwJERTEhMB8GA1UECgwYSW5maW5lb24gVGVjaG5vbG9naWVzIEFHMRMwEQYD
VQQLDApPUFRJR0EoVE0pMSswKQYDVQQDDCJJbmZpbmVvbiBPUFRJR0EoVE0pIFRy
dXN0IE0gQ0EgMTAxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElzN3NK10I6FL
9A/U7h0nr47QWuh5cMdN/imIm0ma0tAeokmueRDwUsWdhVFKghXi1j5HMM37XMFT
u8wAp+ZAi6N9MHswHQYDVR0OBBYEFDwwjFzViuijXTKA5FSDsv/Nhk0jMA4GA1Ud
DwEB/wQEAwIABDASBgNVHRMBAf8ECDAGAQH/AgEAMBUGA1UdIAQOMAwwCgYIKoIU
AEQBFAEwHwYDVR0jBBgwFoAUtBiFyEpKxRJ68kA53sT1ix5+StEwCgYIKoZIzj0E
AwMDaAAwZQIxAJ582emCY3u8UWVmqcW6MOylCgw7mB3HJEo9/l3TAEiY7pI4A661
WvolTXNMikx7gwIwc1jw/vO6jjN4TDP/N+pvNXKzVpAytc4+atGsR3lCAbGsN63i
U9h2spNYuRpTEXbN
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIICWzCCAeKgAwIBAgIBBDAKBggqhkjOPQQDAzB3MQswCQYDVQQGEwJERTEhMB8G
A1UECgwYSW5maW5lb24gVGVjaG5vbG9naWVzIEFHMRswGQYDVQQLDBJPUFRJR0Eo
VE0pIERldmljZXMxKDAmBgNVBAMMH0luZmluZW9uIE9QVElHQShUTSkgRUNDIFJv
b3QgQ0EwHhcNMTMwNzI2MDAwMDAwWhcNNDMwNzI1MjM1OTU5WjB3MQswCQYDVQQG
EwJERTEhMB8GA1UECgwYSW5maW5lb24gVGVjaG5vbG9naWVzIEFHMRswGQYDVQQL
DBJPUFRJR0EoVE0pIERldmljZXMxKDAmBgNVBAMMH0luZmluZW9uIE9QVElHQShU
TSkgRUNDIFJvb3QgQ0EwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQm1HxLVgvAu1q2
GM+ymTz12zdTEu0JBVG9CdsVEJv/pE7pSWOlsG3YwU792YAvjSy7zL+WtDK40KGe
Om8bSWt46QJ00MQUkYxz6YqXbb14BBr06hWD6u6IMBupNkPd9pKjQjBAMB0GA1Ud
DgQWBBS0GIXISkrFEnryQDnexPWLHn5K0TAOBgNVHQ8BAf8EBAMCAAYwDwYDVR0T
AQH/BAUwAwEB/zAKBggqhkjOPQQDAwNnADBkAjA6QZcV8DjjbPuKjKDZQmTRywZk
MAn8wE6kuW3EouVvBt+/2O+szxMe4vxj8R6TDCYCMG7c9ov86ll/jDlJb/q0L4G+
+O3Bdel9P5+cOgzIGANkOPEzBQM3VfJegfnriT/kaA==
-----END CERTIFICATE-----

```

**Comment by Darsh-Dev** [comment]
@ayushev Using shared the root chain CA, verified it successfully with openssl. 

Now, I'm trying with, 
> pal_crypt_verify_certificate(optiga_ca_certificate, sizeof(optiga_ca_certificate), chip_cert, chip_cert_size);

I have created DER for above shared root chain CA, and give it to optiga_ca_certificate. But getting failed.  (also tried with Infineon OPTIGA(TM) Trust M CA 101.pem, but know luck)

**Comment by ayushev** [comment]
Hi, for the API you use, there is an [example](https://github.com/Infineon/optiga-trust-m/blob/0d68153d40a877ee08d3e62bec41d38597106d3d/examples/utilities/authenticate_chip/example_authenticate_chip.c#L564)
The CA should be a **DER encoded (in hex)** generic X.509 certificate (mbedlts does allow to use no a full chain for the verification), like [here](https://github.com/Infineon/optiga-trust-m/blob/0d68153d40a877ee08d3e62bec41d38597106d3d/examples/utilities/authenticate_chip/example_authenticate_chip.c#L162). The device certificate shuld be as well a DER encoded (in hex) generic X.509 certificate (have a loom on how its striped from the optiga tags [here](https://github.com/Infineon/optiga-trust-m/blob/0d68153d40a877ee08d3e62bec41d38597106d3d/examples/utilities/authenticate_chip/example_authenticate_chip.c#L280)). 

The example above does exactly what you do, checks against the intemdiate CA the device certificate.

**Comment by Darsh-Dev** [comment]
Hi, @ayushev 

We have also verified with XMC4800 & Optiga TrustM kit. I have download the code from [here](https://github.com/Infineon/mbedtls-optiga-trust-m). and set the "**AUTH_TEST** " as 1.

Its **failed** to verify **example_authenticate_chip**
> 15 12098 [Echo0] +++++Authentication Test+++++
> 16 12098 [Echo0] >example_authenticate_chip()
> 17 12098 [Echo0] >pal_crypt_init()
> 18 12108 [Echo0] pal_crypt_init: Random number (len=32)
> 19 12130 [Echo0] <pal_crypt_init()
> 20 12130 [Echo0] Read default cert and verify it
> 21 12130 [Echo0] >read_chip_cert()
> 22 12178 [Echo0] mbedtls_x509_crt_verify failed (status=ffffd900)
> 23 12178 [Echo0] Error: verify cert failed. (status=0x3003)
> 24 12178 [Echo0] <example_authenticate_chip()
> 25 12178 [Echo0] Auth done count=1
> 26 12178 [Echo0] +++++Auth Test Completed+++++

[FYI - not changed anything in the code]
